# Generated by Django 3.1 on 2020-08-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_dates',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
